### ISSUE TITLE
To include new item value in items.json/xml

### ISSUE THREAD

**Issue by tstkenny** [broderickhyman/ao-bin-dumps#47]
Since Call to arms updated the item values of all items (e.g. Pork Pie, new item value is 576), is it possible to have this value to be included in the dump?  The figure is necessary in usage fee calculations.  Thank you!

**Comment by raspher** [comment]
Author is not active on github since May 26. Feel free to fork and update, don't forget to create pull request 🙂

**Comment by raspher** [comment]
@tstkenny i've updated all data, changes are currently in PR. Pork Pie however seems not have itemvalue at all (as i see in json). Line 39164.

#49

**Comment by phendryx** [comment]
Owner might be inactive, but I'm not. I do updates. I might be a day behind since I don't play the game and only run the launcher every few days. I don't check issues or PRs often unless someone points them out, but I keep the ball rolling well enough.

**Comment by phendryx** [comment]
As of yesterdays update in items.txt:

![image](https://user-images.githubusercontent.com/482311/179969577-e41f50b0-a133-406e-bbab-51791dab45e5.png)

Items.json:

![image](https://user-images.githubusercontent.com/482311/179969762-9821d798-8176-44db-b7fd-d75fbf83ba75.png)
